apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: azure-rag-app-shadow-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: azure-rag-app-shadow-svc
            port:
              number: 80
