apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: azure-rag-app-shadow-vsvc
spec:
  hosts:
  - "*"
  http:
  - name: primary
    route:
    - destination:
        host: azure-rag-app-shadow-stable
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: azure-rag-app-shadow-dr
spec:
  host: azure-rag-app-shadow-stable
  subsets:
  - name: stable
    labels:
      app: azure-rag-app-shadow
  - name: canary
    labels:
      app: azure-rag-app-shadow
