apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: azure-rag-app-shadow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-rag-app-shadow

  template:
    metadata:
      labels:
        app: azure-rag-app-shadow
    spec:
      containers:
      - name: azure-rag-app-shadow
        image: kaustavcontainerregistry.azurecr.io/azure-rag-app-shadow:latest
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 4
            memory: 4Gi

  strategy:
    canary:
      stableService: azure-rag-app-shadow-stable
      canaryService: azure-rag-app-shadow-canary

      trafficRouting:
        istio:
          virtualService:
            name: azure-rag-app-shadow-vsvc
            routes:
            - primary

      steps:
      - setMirrorRoute:
          name: shadow-mirror
          match:
          - headers:
              x-enable-shadow:
                exact: "true"
      - pause: {}