apiVersion: v1
kind: Service
metadata:
  name: azure-rag-app-shadow-svc
spec:
  selector:
    app: azure-rag-app-shadow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 # Placeholder if a web server is added
  type: ClusterIP
