name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AZURE_RAG_APP_ENV

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    #- name: Lint
    #  run: |
    #    python -m flake8 .
        
    - name: Run tests with pytest
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        PYTHONPATH=. pytest tests/

    - name: Build Docker Image 
      run: |
        docker build -t kaustavcontainerregistry.azurecr.io/azure-rag-app-shadow:${{ github.sha }} .

    - name: Login To Azure Container Registry 
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push kaustavcontainerregistry.azurecr.io/azure-rag-app-shadow:${{ github.sha }}

# ###########################################Deployment (Handled by Argo CD)#####################################################################    

#     - name: Azure Login
#       uses: azure/login@v2
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - name: Set AKS Context
#       uses: azure/aks-set-context@v3
#       with:
#         resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
#         cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

#     - name: Create Kubernetes Generic Secret
#       uses: azure/k8s-create-secret@v4
#       with:
#         namespace: default # Change this if using a different namespace
#         secret-type: generic
#         secret-name: azure-rag-secrets
#         string-data: |
#           {
#             "AZURE_STORAGE_CONNECTION_STRING": "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}",
#             "AZURE_OPENAI_ENDPOINT": "${{ secrets.AZURE_OPENAI_ENDPOINT }}",
#             "AZURE_OPENAI_API_VERSION": "${{ secrets.AZURE_OPENAI_API_VERSION }}",
#             "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME": "${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME }}"
#           }


#     - name: Deploy to AKS
#       uses: azure/k8s-deploy@v4
#       with:
#         namespace: default
#         manifests: |
#           k8s/rollout.yaml
#           k8s/service.yaml
#         images: |
#           kaustavcontainerregistry.azurecr.io/azure-rag-app:${{ github.sha }}
